// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SgiForm.Infrastructure.Persistence;

#nullable disable

namespace SgiForm.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240101000000_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Model snapshot vacío — el schema real está en los scripts SQL
            modelBuilder
                .HasDefaultSchema("sf")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
